/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/routes/__root'
import { Route as AppRouteRouteImport } from './app/routes/app/route'
import { Route as IndexRouteImport } from './app/routes/index'
import { Route as AppIndexRouteImport } from './app/routes/app/index'
import { Route as AppSettingsRouteImport } from './app/routes/app/settings'
import { Route as AppAuthenticatedRouteRouteImport } from './app/routes/app/_authenticated/route'
import { Route as AppArticlesIndexRouteImport } from './app/routes/app/articles/index'
import { Route as AppAccountsIndexRouteImport } from './app/routes/app/accounts/index'
import { Route as AppArticlesArticleIdRouteImport } from './app/routes/app/articles/$articleId'
import { Route as AppAuthenticatedProfileRouteImport } from './app/routes/app/_authenticated/profile'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAuthenticatedRouteRoute = AppAuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppArticlesIndexRoute = AppArticlesIndexRouteImport.update({
  id: '/articles/',
  path: '/articles/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAccountsIndexRoute = AppAccountsIndexRouteImport.update({
  id: '/accounts/',
  path: '/accounts/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppArticlesArticleIdRoute = AppArticlesArticleIdRouteImport.update({
  id: '/articles/$articleId',
  path: '/articles/$articleId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAuthenticatedProfileRoute = AppAuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppAuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppAuthenticatedRouteRouteWithChildren
  '/app/settings': typeof AppSettingsRoute
  '/app/': typeof AppIndexRoute
  '/app/profile': typeof AppAuthenticatedProfileRoute
  '/app/articles/$articleId': typeof AppArticlesArticleIdRoute
  '/app/accounts/': typeof AppAccountsIndexRoute
  '/app/articles/': typeof AppArticlesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppIndexRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/profile': typeof AppAuthenticatedProfileRoute
  '/app/articles/$articleId': typeof AppArticlesArticleIdRoute
  '/app/accounts': typeof AppAccountsIndexRoute
  '/app/articles': typeof AppArticlesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/app/_authenticated': typeof AppAuthenticatedRouteRouteWithChildren
  '/app/settings': typeof AppSettingsRoute
  '/app/': typeof AppIndexRoute
  '/app/_authenticated/profile': typeof AppAuthenticatedProfileRoute
  '/app/articles/$articleId': typeof AppArticlesArticleIdRoute
  '/app/accounts/': typeof AppAccountsIndexRoute
  '/app/articles/': typeof AppArticlesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/settings'
    | '/app/'
    | '/app/profile'
    | '/app/articles/$articleId'
    | '/app/accounts/'
    | '/app/articles/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/app/settings'
    | '/app/profile'
    | '/app/articles/$articleId'
    | '/app/accounts'
    | '/app/articles'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/_authenticated'
    | '/app/settings'
    | '/app/'
    | '/app/_authenticated/profile'
    | '/app/articles/$articleId'
    | '/app/accounts/'
    | '/app/articles/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/_authenticated': {
      id: '/app/_authenticated'
      path: ''
      fullPath: '/app'
      preLoaderRoute: typeof AppAuthenticatedRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/articles/': {
      id: '/app/articles/'
      path: '/articles'
      fullPath: '/app/articles/'
      preLoaderRoute: typeof AppArticlesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/accounts/': {
      id: '/app/accounts/'
      path: '/accounts'
      fullPath: '/app/accounts/'
      preLoaderRoute: typeof AppAccountsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/articles/$articleId': {
      id: '/app/articles/$articleId'
      path: '/articles/$articleId'
      fullPath: '/app/articles/$articleId'
      preLoaderRoute: typeof AppArticlesArticleIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/_authenticated/profile': {
      id: '/app/_authenticated/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppAuthenticatedProfileRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
  }
}

interface AppAuthenticatedRouteRouteChildren {
  AppAuthenticatedProfileRoute: typeof AppAuthenticatedProfileRoute
}

const AppAuthenticatedRouteRouteChildren: AppAuthenticatedRouteRouteChildren = {
  AppAuthenticatedProfileRoute: AppAuthenticatedProfileRoute,
}

const AppAuthenticatedRouteRouteWithChildren =
  AppAuthenticatedRouteRoute._addFileChildren(
    AppAuthenticatedRouteRouteChildren,
  )

interface AppRouteRouteChildren {
  AppAuthenticatedRouteRoute: typeof AppAuthenticatedRouteRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppArticlesArticleIdRoute: typeof AppArticlesArticleIdRoute
  AppAccountsIndexRoute: typeof AppAccountsIndexRoute
  AppArticlesIndexRoute: typeof AppArticlesIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAuthenticatedRouteRoute: AppAuthenticatedRouteRouteWithChildren,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppArticlesArticleIdRoute: AppArticlesArticleIdRoute,
  AppAccountsIndexRoute: AppAccountsIndexRoute,
  AppArticlesIndexRoute: AppArticlesIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
